//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrustAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntityTRUST : DbContext
    {
        public EntityTRUST()
            : base("name=EntityTRUST")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cn_Users> Cn_Users { get; set; }
        public virtual DbSet<Ms_Customer_CompanyGroups> Ms_Customer_CompanyGroups { get; set; }
        public virtual DbSet<Ms_Customers> Ms_Customers { get; set; }
        public virtual DbSet<Ms_Vehicle_Brands> Ms_Vehicle_Brands { get; set; }
        public virtual DbSet<Ms_Vehicle_Models> Ms_Vehicle_Models { get; set; }
        public virtual DbSet<Ms_Vehicles> Ms_Vehicles { get; set; }
        public virtual DbSet<Tr_BSTKBefores> Tr_BSTKBefores { get; set; }
    }
}
