//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrustAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ms_Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ms_Customers()
        {
            this.Tr_BSTKBefores = new HashSet<Tr_BSTKBefores>();
        }
    
        public int Customer_ID { get; set; }
        public Nullable<int> CompanyGroup_ID { get; set; }
        public string Company_Name { get; set; }
        public string PT { get; set; }
        public bool Tbk { get; set; }
        public string Address { get; set; }
        public Nullable<int> City_ID { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string PIC_Name { get; set; }
        public string PIC_Phone { get; set; }
        public string PIC_Email { get; set; }
        public string Notes { get; set; }
        public string Customer_Class { get; set; }
        public string Credit_Rating { get; set; }
        public string Line_of_Business { get; set; }
        public Nullable<decimal> Authorized_Capital { get; set; }
        public string Authorized_Signer_Name1 { get; set; }
        public string Authorized_Signer_Position1 { get; set; }
        public string Authorized_Signer_Name2 { get; set; }
        public string Authorized_Signer_Position2 { get; set; }
        public string IntroducedBy { get; set; }
        public string NPWP { get; set; }
        public string Account { get; set; }
        public string Bank { get; set; }
        public Nullable<bool> IsStamped { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Published { get; set; }
        public Nullable<bool> IsKYC { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Cn_Users Cn_Users { get; set; }
        public virtual Cn_Users Cn_Users1 { get; set; }
        public virtual Ms_Customer_CompanyGroups Ms_Customer_CompanyGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tr_BSTKBefores> Tr_BSTKBefores { get; set; }
    }
}
