//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrustAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ms_Vehicles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ms_Vehicles()
        {
            this.Tr_BSTKBefores = new HashSet<Tr_BSTKBefores>();
        }
    
        public int Vehicle_id { get; set; }
        public string license_no { get; set; }
        public string Tmp_Plat { get; set; }
        public Nullable<int> Model_ID { get; set; }
        public string type { get; set; }
        public string color { get; set; }
        public Nullable<int> year { get; set; }
        public string chassis_no { get; set; }
        public string machine_no { get; set; }
        public string title_no { get; set; }
        public string serial_no { get; set; }
        public string registration_no { get; set; }
        public Nullable<System.DateTime> registration_expdate { get; set; }
        public string insurance_no { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> acquisition { get; set; }
        public Nullable<decimal> coverage { get; set; }
        public string comment { get; set; }
        public int status { get; set; }
        public Nullable<System.DateTime> date_insurance_start { get; set; }
        public Nullable<System.DateTime> date_insurance_end { get; set; }
        public Nullable<System.DateTime> date_insurance_mod { get; set; }
        public Nullable<System.DateTime> date_book { get; set; }
        public string STNK_No { get; set; }
        public Nullable<System.DateTime> STNK_Publish { get; set; }
        public Nullable<System.DateTime> STNK_Yearly_Renewal { get; set; }
        public Nullable<System.DateTime> STNK_5Year_Renewal { get; set; }
        public Nullable<int> STNK_Month { get; set; }
        public string STNK_Name { get; set; }
        public string STNK_Address { get; set; }
        public Nullable<int> CC { get; set; }
        public string Fuel { get; set; }
        public string NoUrutBuku { get; set; }
        public Nullable<System.DateTime> DO_date { get; set; }
        public Nullable<System.DateTime> Vehicle_Come { get; set; }
        public Nullable<System.DateTime> STNK_Receipt { get; set; }
        public string PO_No { get; set; }
        public Nullable<decimal> Harga_Beli { get; set; }
        public Nullable<System.DateTime> Kwitansi_Date { get; set; }
        public string Kwitansi_No { get; set; }
        public Nullable<System.DateTime> FakturPajak_Date { get; set; }
        public string FakturPajak_No { get; set; }
        public string VAT { get; set; }
        public string Dealer { get; set; }
        public Nullable<int> ContractDetail_ID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Cn_Users Cn_Users { get; set; }
        public virtual Cn_Users Cn_Users1 { get; set; }
        public virtual Ms_Vehicle_Models Ms_Vehicle_Models { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tr_BSTKBefores> Tr_BSTKBefores { get; set; }
    }
}
