

namespace TrustAPI.Models.Model
{
    public class Tr_BSTKBefore
    {
        public string Nama_Customer { get; set; }
        public string Nomor_Plat_Kendaraan { get; set; }
        public string Automatic_Light_Switch { get; set; }
        public string Automatic_Light_Switch_Ket { get; set; }
        public string Lampu_Kecil { get; set; }
        public string Lampu_Kecil_Ket { get; set; }
        public string Lampu_Dekat { get; set; }
        public string Lampu_Dekat_Ket { get; set; }
        public string Lampu_Jauh { get; set; }
        public string Lampu_Jauh_Ket { get; set; }
        public string Lampu_Kabut_Fog_Lamp { get; set; }
        public string Lampu_Kabut_Fog_Lamp_Ket { get; set; }
        public string Lampu_Sign_Depan { get; set; }
        public string Lampu_Sign_Depan_Ket { get; set; }
        public string Lampu_Sign_Belakang { get; set; }
        public string Lampu_Sign_Belakang_Ket { get; set; }
        public string Lampu_Belakang { get; set; }
        public string Lampu_Belakang_Ket { get; set; }
        public string Lampu_Rem { get; set; }
        public string Lampu_Rem_Ket { get; set; }
        public string Lampu_Mundur { get; set; }
        public string Lampu_Mundur_Ket { get; set; }
        public string Lampu_Dashboard { get; set; }
        public string Lampu_Dashboard_Ket { get; set; }
        public string Lampu_Plafond_Depan_dan_Belakang { get; set; }
        public string Lampu_Plafond_Depan_dan_Belakang_Ket { get; set; }
        public string Klakson { get; set; }
        public string Klakson_Ket { get; set; }
        public string Antena { get; set; }
        public string Antena_Ket { get; set; }
        public string Tape_Radio_CD_DVD_TV_Player { get; set; }
        public string Tape_Radio_CD_DVD_TV_Player_Ket { get; set; }
        public string Remote_Tape_Radio_CD_DVD_TV_Player { get; set; }
        public string Remote_Tape_Radio_CD_DVD_TV_Player_Ket { get; set; }
        public string Alarm_Remote_Key { get; set; }
        public string Alarm_Remote_Key_Ket { get; set; }
        public string Central_Lock { get; set; }
        public string Central_Lock_Ket { get; set; }
        public string Power_Window { get; set; }
        public string Power_Window_Ket { get; set; }
        public string Switch_Mirror { get; set; }
        public string Switch_Mirror_Ket { get; set; }
        public string Air_Conditioner { get; set; }
        public string Air_Conditioner_Ket { get; set; }
        public string Safety_Belt { get; set; }
        public string Safety_Belt_Ket { get; set; }
        public string Karpet { get; set; }
        public string Karpet_Ket { get; set; }
        public string Lighter { get; set; }
        public string Lighter_Ket { get; set; }
        public string Asbak { get; set; }
        public string Asbak_Ket { get; set; }
        public string Sarung_Jok { get; set; }
        public string Sarung_Jok_Ket { get; set; }
        public string Sandaran_Kepala { get; set; }
        public string Sandaran_Kepala_Ket { get; set; }
        public string Spion_Dalam { get; set; }
        public string Spion_Dalam_Ket { get; set; }
        public string Wiper_Blade { get; set; }
        public string Wiper_Blade_Ket { get; set; }
        public string Windshield_Washer { get; set; }
        public string Windshield_Washer_Ket { get; set; }
        public string Talang_Air { get; set; }
        public string Talang_Air_Ket { get; set; }
        public string Fender_Lumpur_Depan_dan_Belakang { get; set; }
        public string Fender_Lumpur_Depan_dan_Belakang_Ket { get; set; }
        public string Spion_Kiri_Kanan { get; set; }
        public string Spion_Kiri_Kanan_Ket { get; set; }
        public string Tutup_Bensin { get; set; }
        public string Tutup_Bensin_Ket { get; set; }
        public string Emblem_Logo { get; set; }
        public string Emblem_Logo_Ket { get; set; }
        public string Kaca_Mobil_dan_Kaca_Film { get; set; }
        public string Kaca_Mobil_dan_Kaca_Film_Ket { get; set; }
        public string STNK { get; set; }
        public string STNK_Ket { get; set; }
        public string Buku_KIR_Stiker_Peneng { get; set; }
        public string Buku_KIR_Stiker_Peneng_Ket { get; set; }
        public string Owners_Manual_Book { get; set; }
        public string Owners_Manual_Book_Ket { get; set; }
        public string Buku_Service { get; set; }
        public string Buku_Service_Ket { get; set; }
        public string Ban_Serep { get; set; }
        public string Ban_Serep_Ket { get; set; }
        public string Kunci_Roda_Busi_Pas_Tang { get; set; }
        public string Kunci_Roda_Busi_Pas_Tang_Ket { get; set; }
        public string Kunci_Stir { get; set; }
        public string Kunci_Stir_Ket { get; set; }
        public string Dongkrak { get; set; }
        public string Dongkrak_Ket { get; set; }
        public string P3K { get; set; }
        public string P3K_Ket { get; set; }
        public string Segitiga_Pengaman { get; set; }
        public string Segitiga_Pengaman_Ket { get; set; }
        public string Lap_Kanebo { get; set; }
        public string Lap_Kanebo_Ket { get; set; }
        public string Foto_Kendaraan_Tampak_Depan { get; set; }
        public string Foto_Kendaraan_Tampak_Depan_decode { get; set; }
        public string Foto_Kendaraan_Tampak_Belakang { get; set; }
        public string Foto_Kendaraan_Tampak_Samping_Kanan { get; set; }
        public string Foto_Kendaraan_Tampak_Samping_Kiri { get; set; }
        public string apar { get; set; }
        public string fuel { get; set; }
        public int? isi_tangki { get; set; }
        public string isi_tangki_ket { get; set; }
        public int? km { get; set; }
        public string velg_ban { get; set; }
        public string tutup_dop { get; set; }
        public string signature { get; set; }
        public string signature_image { get; set; }
    }
}